// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kidtvipooobyfmlojjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZHR2aXBvb29ieWZtbG9qandqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjI0NTcsImV4cCI6MjA2ODMzODQ1N30.4bX42Cq9LjRbSFMCP6DwdNCGHMSpFQ8rgeE5p2S-V4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});